#!/usr/bin/env python3
#  Copyright (c) 2022, Dr Rahim Lakhoo, razman786@gmail.com.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program. If not,
# see <https://www.gnu.org/licenses/>.
#

from pathlib import Path

from PySide6 import QtCore
from PySide6.QtCore import QSize, Slot, QSettings
from PySide6.QtGui import QIcon, QAction, QScreen, Qt, QIntValidator, QPalette, QColor
from PySide6.QtWidgets import QApplication, QMainWindow, QSystemTrayIcon, QMenu, QMessageBox, QDialog, QPushButton, \
    QCheckBox, QLineEdit, QLabel, QFormLayout


class I8kGui(QMainWindow):
    def __init__(self):
        super(I8kGui, self).__init__()
        self.settings = QSettings()
        self.always_on = False
        self.monitor_interval = 1000
        self.always_on_checkbox = QCheckBox()
        self.interval_input = QLineEdit()
        self.settings_dialog = QDialog()
        self.info_dialog = QDialog()
        self.save_button = QPushButton("Save", self.settings_dialog)
        self.i8k_format_version = QLabel("1")
        self.bios_version = QLabel("1")
        self.service_tag = QLabel("N/A")
        self.power_status = QLabel("N/A")
        self.button_status = QLabel("N/A")
        self.load_settings()
        self.monitorTimer = QtCore.QTimer(self)
        self.monitorTimer.timeout.connect(self.refresh_monitor)
        self.monitorTimer.setInterval(self.monitor_interval)
        self.create_settings_dialog()
        self.create_info_dialog()
        self.tray = None
        self.tray_menu = None
        self.first_load = True
        self.critical_error = False
        self.degree_sign = u'\N{DEGREE SIGN}'
        self.cpu_temp = QAction("CPU Temp:                ")
        self.left_fan_rpm = QAction("Left Fan RPM:          ")
        self.right_fan_rpm = QAction("Right Fan RPM:       ")
        self.left_fan_status = QAction("Left Fan Status:      ")
        self.right_fan_status = QAction("Right Fan Status:   ")
        self.load_sys_tray()

    def close_app(self):
        self.save_settings()
        app.quit()

    def load_settings(self):
        if self.settings.value('always_on').lower() == 'true':
            self.always_on = True
            self.always_on_checkbox.setCheckState(Qt.Checked)
        else:
            self.always_on = False
            self.always_on_checkbox.setCheckState(Qt.Unchecked)

        self.monitor_interval = int(self.settings.value('interval', 1000))

    def save_settings(self):
        self.settings.setValue('always_on', self.always_on)
        self.settings.setValue('interval', self.monitor_interval)

    def always_collect(self, checked):
        if checked == Qt.Checked:
            self.monitor_interval = int(self.interval_input.text())
            self.monitorTimer.setInterval(self.monitor_interval)
            self.always_on = True
            if not self.monitorTimer.isActive():
                self.monitorTimer.start()
            else:
                self.monitorTimer.stop()
                self.monitorTimer.start()
        else:
            self.always_on = False
            if self.monitorTimer.isActive():
                self.monitorTimer.stop()

    def save_dialog_settings(self):
        if self.monitor_interval != int(self.interval_input.text()):
            self.monitor_interval = int(self.interval_input.text())
            self.monitorTimer.setInterval(self.monitor_interval)
            if self.monitorTimer.isActive():
                self.monitorTimer.stop()
                self.monitorTimer.start()
        self.save_settings()
        self.settings_dialog.close()

    def close_info_dialog(self):
        self.info_dialog.close()

    def create_info_dialog(self):
        close_button = QPushButton("close", self.info_dialog)
        close_button.setMaximumWidth(100)
        close_button.clicked.connect(self.close_info_dialog)

        f_layout = QFormLayout()
        f_layout.addRow("i8k Format Version: ", self.i8k_format_version)
        f_layout.addRow("BIOS Version: ", self.bios_version)
        f_layout.addRow("Service Tag: ", self.service_tag)
        f_layout.addRow("A/C Power Supply: ", self.power_status)
        f_layout.addRow("Button Status: ", self.button_status)
        f_layout.addRow(" ", None)
        f_layout.addWidget(close_button)
        self.info_dialog.setLayout(f_layout)

        # set dialog geometry
        self.info_dialog.setWindowTitle("Information")
        self.info_dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        self.info_dialog.setMaximumWidth(400)
        self.info_dialog.setMaximumHeight(200)
        center_point = QScreen.availableGeometry(QApplication.primaryScreen()).center()
        fg = self.info_dialog.frameGeometry()
        fg.moveCenter(center_point)
        self.info_dialog.move(fg.topLeft())

    def create_settings_dialog(self):
        self.save_button.setMaximumWidth(100)
        self.always_on_checkbox.setText("Collect statistics continuously")
        self.always_on_checkbox.stateChanged.connect(self.always_collect)
        self.interval_input.setValidator(QIntValidator())
        self.interval_input.setMaxLength(6)
        self.interval_input.setText(str(self.monitor_interval))

        self.save_button.clicked.connect(self.save_dialog_settings)
        f_layout = QFormLayout()
        f_layout.addRow(self.always_on_checkbox)
        f_layout.addRow(" ", None)
        f_layout.addRow("Monitoring Interval (milliseconds):", self.interval_input)
        f_layout.addRow(" ", None)
        f_layout.addRow(self.save_button)
        self.settings_dialog.setLayout(f_layout)

        # set dialog geometry
        self.settings_dialog.setWindowTitle("Settings")
        self.settings_dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        self.settings_dialog.setMaximumWidth(400)
        self.settings_dialog.setMaximumHeight(200)
        center_point = QScreen.availableGeometry(QApplication.primaryScreen()).center()
        fg = self.settings_dialog.frameGeometry()
        fg.moveCenter(center_point)
        self.settings_dialog.move(fg.topLeft())

    def load_sys_tray(self):
        self.tray = QSystemTrayIcon(self)
        if self.tray.isSystemTrayAvailable():
            icon = QIcon(str(Path.home()) + "/.local/share/icons/i8kgui_icon.png")
            if icon.pixmap(QSize(64, 64)).isNull():
                icon = QIcon('icons/i8kgui_icon.png')
            self.tray.setIcon(icon)
            self.tray.activated.connect(self.status)
            self.tray.messageClicked.connect(self.message_clicked)

            # workaround because tray activated only works with double click
            self.tray_menu = QMenu()
            self.tray_menu.aboutToShow.connect(self.monitor)
            self.tray_menu.aboutToHide.connect(self.stop_monitor)

            # setup display
            self.tray_menu.addAction(self.cpu_temp)
            self.tray_menu.addAction(self.left_fan_rpm)
            self.tray_menu.addAction(self.right_fan_rpm)
            self.tray_menu.addAction(self.left_fan_status)
            self.tray_menu.addAction(self.right_fan_status)
            self.tray_menu.addSeparator()

            # add info, settings and quit menu items
            action_info = self.tray_menu.addAction("Information")
            action_info.triggered.connect(self.show_info)
            action_settings = self.tray_menu.addAction("Settings")
            action_settings.triggered.connect(self.show_settings)
            action_quit = self.tray_menu.addAction("Quit")
            action_quit.triggered.connect(self.close_app)

            self.tray.setContextMenu(self.tray_menu)
            self.tray.setToolTip("i8kgui")
            self.tray.setVisible(True)
        else:
            QMessageBox.critical(None, "i8kgui", "Unable to locate system tray on this system.")
            self.close_app()

    @Slot()
    def message_clicked(self):
        self.close_app()

    def read_proc(self):
        # read i8k values from /proc then update the system tray
        # and send a fake click to initiate live updating while
        # the system tray is in active use.
        if not self.critical_error:
            try:
                i8k_proc = open('/proc/i8k', 'r')
            except IOError as e:
                self.critical_error = True
                self.tray.showMessage("i8kgui", f"Error cannot find i8k module. Please install/start i8kutils.\n\n{e}",
                                      icon=QSystemTrayIcon.Critical, msecs=10000)
            else:
                line = i8k_proc.readline()
                i8k_proc.close()
                split_line = line.split(' ')
                self.cpu_temp.setText(f"CPU Temp:                {split_line[3]}{self.degree_sign}C")
                self.left_fan_rpm.setText(f"Left Fan RPM:          {split_line[6]}")
                self.right_fan_rpm.setText(f"Right Fan RPM:       {split_line[7]}")
                self.left_fan_status.setText(f"Left Fan Status:      {split_line[4]}")
                self.right_fan_status.setText(f"Right Fan Status:   {split_line[5]}")

                self.i8k_format_version.setText(split_line[0])
                self.bios_version.setText(split_line[1])
                self.service_tag.setText(split_line[2])
                self.power_status.setText(split_line[8])
                self.button_status.setText(split_line[9])

                self.tray.activated.emit(QSystemTrayIcon.Trigger)  # send fake single-click event as workaround

    def status(self, reason):
        # start live updating of values if system tray is in active use,
        # and employ workaround for timer being started upon load.
        if reason == QSystemTrayIcon.ActivationReason.Trigger:
            if not self.monitorTimer.isActive():
                if not self.first_load:
                    self.monitorTimer.start()
                else:
                    self.first_load = False  # workaround to not start QTimer when tray is loaded first time

    def monitor(self):
        self.read_proc()

    def refresh_monitor(self):
        self.read_proc()

    def stop_monitor(self):
        if not self.always_on:
            if self.monitorTimer.isActive():
                self.monitorTimer.stop()

    def show_settings(self):
        self.settings_dialog.show()

    def show_info(self):
        self.info_dialog.show()


if __name__ == '__main__':
    app = QApplication([])
    app.setOrganizationName("i8kgui")
    app.setApplicationName("i8kgui")
    app.setApplicationVersion("0.2")

    # setup Dark Mode QPalette - initial setup
    palette = QPalette()
    palette.setColor(QPalette.Window, QColor(53, 53, 53))
    palette.setColor(QPalette.WindowText, Qt.white)
    palette.setColor(QPalette.Light, QColor(68, 68, 68))
    palette.setColor(QPalette.Base, QColor(25, 25, 25))
    palette.setColor(QPalette.AlternateBase, QColor(53, 53, 53))
    palette.setColor(QPalette.ToolTipBase, Qt.white)
    palette.setColor(QPalette.ToolTipText, Qt.black)
    palette.setColor(QPalette.Text, Qt.white)
    palette.setColor(QPalette.Button, QColor(53, 53, 53))
    palette.setColor(QPalette.ButtonText, Qt.white)
    palette.setColor(QPalette.BrightText, Qt.red)
    palette.setColor(QPalette.Link, QColor(42, 130, 218))
    palette.setColor(QPalette.Highlight, QColor(42, 130, 218, 192))
    palette.setColor(QPalette.HighlightedText, Qt.white)

    # setup Dark Mode disabled QPalette
    palette.setColor(QPalette.Disabled, QPalette.Window, Qt.black)
    palette.setColor(QPalette.Disabled, QPalette.WindowText, QColor(255, 255, 255, 128))
    palette.setColor(QPalette.Disabled, QPalette.Base, QColor(68, 68, 68))
    palette.setColor(QPalette.Disabled, QPalette.Text, QColor(255, 255, 255, 128))
    palette.setColor(QPalette.Disabled, QPalette.Button, QColor(53, 53, 53, 128))
    palette.setColor(QPalette.Disabled, QPalette.ButtonText, QColor(255, 255, 255, 128))
    palette.setColor(QPalette.Disabled, QPalette.BrightText, Qt.black)
    palette.setColor(QPalette.Disabled, QPalette.Link, Qt.black)
    palette.setColor(QPalette.Disabled, QPalette.Highlight, Qt.black)
    palette.setColor(QPalette.Disabled, QPalette.HighlightedText, Qt.black)

    # add Dark Mode to i8kgui
    app.setPalette(palette)

    app.setQuitOnLastWindowClosed(False)
    tray = I8kGui()

    app.exec()
