#!/bin/bash
#  Copyright (c) 2022, Dr Rahim Lakhoo, razman786@gmail.com.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program. If not,
# see <https://www.gnu.org/licenses/>.
#

# display help
display_usage() {
	echo -e "\nUsage: $0 [OPTION]\n"
	echo -e "-e, --enable     enable BIOS thermal control\n"
	echo -e "-d, --disable     disable BIOS thermal control\n"
	}

# check whether user had supplied -h or --help.
if [[ ( $1 == "--help") ||  $1 == "-h" ]]
then
	display_usage
	exit 0
fi

if [[ ( $1 == "--enable") ||  $1 == "-e" ]]
then
	status="enable"
fi

if [[ ( $1 == "--disable") ||  $1 == "-d" ]]
then
	status="disable"
fi

if [[ ! -f "/usr/sbin/smbios-thermal-ctl" ]]
then
  printf "Error smbios-thermal-ctl not found" >&2
  exit 1
elif [[ ! -f "/etc/systemd/system/multi-user.target.wants/i8kmon.service" ]]
then
  printf "Error i8kmon.service not found" >&2
  exit 1
elif [[ ! -f "/etc/systemd/system/multi-user.target.wants/dell-bios-fan-control.service" ]]
then
  printf "Error dell-bios-fan-control.service not found" >&2
  exit 1
fi

if [[ $status == "enable" ]]
then
  is_active=$(systemctl is-active i8kmon.service)
  if [[ $is_active == 'active' ]]
  then
    systemctl stop i8kmon.service && systemctl stop dell-bios-fan-control.service
  fi
    smbios-thermal-ctl -i | grep -A 4 'Supported Thermal Modes'
    smbios-thermal-ctl -g | grep -A 1 'Current Thermal Modes'
else
  is_active=$(systemctl is-active i8kmon.service)
  if [[ $is_active == 'active' ]]
  then
    systemctl start dell-bios-fan-control.service && systemctl start i8kmon.service
  fi
    smbios-thermal-ctl -i | grep -A 4 'Supported Thermal Modes'
    smbios-thermal-ctl -g | grep -A 1 'Current Thermal Modes'
fi
